name: aplikasi_flutter
description: Aplikasi Flutter Pertama

# Naikkan angkanya saat ingin merilis UPDATE baru (misal dari +1 ke +2)
version: 1.0.2+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
