name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Generate Android Files & Secure Pubspec
        run: |
          # 1. Backup pubspec.yaml milikmu agar versi (misal 1.0.3+7) tidak hilang/di-reset
          cp pubspec.yaml pubspec.yaml.bak
          
          # 2. Buat folder android secara otomatis
          flutter create . --platforms=android --android-language kotlin --org com.oetankayoe
          
          # 3. Kembalikan pubspec.yaml milikmu yang berisi kode & versi terbaru
          cp pubspec.yaml.bak pubspec.yaml
          
          # 4. Install dependencies
          flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flutter-APK-Release
          path: build/app/outputs/flutter-apk/app-release.apk
