name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch: # Mengizinkan pemicuan build secara manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java / JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle' # Mengaktifkan caching otomatis untuk file Gradle & dependensi

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease --parallel --build-cache

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk
 
