name: Generate Keystore Base64

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Key & Convert to Base64
        run: |
          keytool -genkeypair -v \
            -keystore upload-keystore.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias upload \
            -dname "CN=OetanKayoe, OU=Dev, O=OetanKayoe, L=Jakarta, ST=Jakarta, C=ID" \
            -storepass "OetanKayoe123!" \
            -keypass "OetanKayoe123!"

          echo "=========================================="
          echo "BERIKUT TEKS BASE64 KEYSTORE KAMU:"
          echo "=========================================="
          base64 -w 0 upload-keystore.jks
          echo ""
          echo "=========================================="
