name: Generate Permanent Keystore File

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.3.0

      - name: Generate Keystore & Commit to Repo
        run: |
          mkdir -p android/app
          
          # Buat Keystore Permanen
          keytool -genkeypair -v \
            -keystore android/app/upload-keystore.jks \
            -storetype JKS \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias upload \
            -dname "CN=OetanKayoe, OU=Dev, O=OetanKayoe, L=Jakarta, ST=Jakarta, C=ID" \
            -storepass "OetanKayoe123!" \
            -keypass "OetanKayoe123!"

          # Simpan (commit) file Keystore fisik ke dalam repositori
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add android/app/upload-keystore.jks
          git commit -m "add permanent release keystore" || true
          git push
